package bankingApp.Transactions;

public class TransactionUtils {

    public enum TransferType {
        DEPOSIT, WITHDRAWAL, TRANSFER
    }

    public enum Country {
        AUSTRALIA, USA, CANADA, UK, GERMANY, FRANCE, JAPAN,
        ITALY, SPAIN, NETHERLANDS, BRAZIL, SOUTH_AFRICA, INDIA,
        CHINA, SOUTH_KOREA, MEXICO, RUSSIA, SWEDEN, NORWAY,
        FINLAND, DENMARK, POLAND, ARGENTINA, CHILE, EGYPT,
        TURKEY, INDONESIA, MALAYSIA, NEW_ZEALAND, BELGIUM,
        AUSTRIA, SWITZERLAND, GREECE, PORTUGAL, HUNGARY,
        CZECH_REPUBLIC, SINGAPORE, THAILAND, PHILIPPINES,
        VIETNAM, SAUDI_ARABIA, UNITED_ARAB_EMIRATES, QATAR,
        KUWAIT, ISRAEL, NIGERIA, KENYA, GHANA, ETHIOPIA,
        PAKISTAN, BANGLADESH, COLOMBIA, VENEZUELA, PERU,
        URUGUAY, CUBA, JAMAICA, HAITI, DOMINICAN_REPUBLIC,
        ICELAND, LUXEMBOURG, CROATIA, SLOVENIA, LATVIA,
        LITHUANIA, ESTONIA, SLOVAKIA, BULGARIA, ROMANIA,
        MOROCCO, ALGERIA, TUNISIA, LIBYA, SUDAN, IRAN,
        IRAQ, SYRIA, JORDAN, LEBANON, OMAN, YEMEN,
        SRI_LANKA, NEPAL, BHUTAN, MALDIVES, KAZAKHSTAN,
        UZBEKISTAN, TURKMENISTAN, KYRGYZSTAN, TAJIKISTAN,
        GEORGIA, ARMENIA, AZERBAIJAN, MONGOLIA, MYANMAR,
        CAMBODIA, LAOS, BRUNEI, FIJI, PAPUA_NEW_GUINEA,
        SOLOMON_ISLANDS, VANUATU, SAMOA, TONGA, MICRONESIA;
    }

    public enum DeviceType {
        MOBILE,
        DESKTOP,
        TABLET,
        ATM,
        POS,
        SMART_WATCH,
    }

    public enum PaymentMethod {
        CREDIT_CARD,
        DEBIT_CARD,
        ONLINE_BANKING,
        PAYPAL,
        APPLE_PAY,
        GOOGLE_WALLET,
        AMAZON_PAY,
        WIRE_TRANSFER,
        CASH_APP,
        VENMO,
        GIFT_CARD,
    }




}
